### ISSUE TITLE
Can't find reset or restart when collision occured 

### ISSUE THREAD

**Issue by benthebear93** [hanruihua/intelligent-robot-simulator#1]
I couldn't find any reset or restart keyboard input for env.
Is there any utils that i don't know?

teleop_key.py example doesent show any Keyborad input for reset too.

**Comment by hanruihua** [comment]
Hi,

There is a function _robots_reset()_  in the env_robot.py to reset the robot states.  

And I have added the interface _env.reset()_ to call this function. In addition, for keyboard input, I added the key 'r' to reset. You can check the functions by example _teleop_key.py_ in the newest version. 

Thanks

**Comment by benthebear93** [comment]
Thx ! ill check!
